[package]
name = "secret-orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19.0"
egui_node_graph = "0.4.0"
tracing-subscriber = "0.3"

anyhow = "1.0.68"
serde_json = "1.0.91"